services:
  escuchowsky:
    build:
      context: ./
      dockerfile: Dockerfile.escuchowsky
    container_name: escuchowsky
    restart: unless-stopped
    environment:
      - LASTFM_API_KEY=${LASTFM_API_KEY}
      - DB_PATH=/app/db/must_hear_rym_new.db
    # read_only: true
    # tmpfs:
    #   - /tmp
    # user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./db:/app/db
      - ./logs/escuchowsky:/app/logs
    networks:
      - musica

  tumtumpa:
    build:
      context: ./
      dockerfile: Dockerfile.tumtumpa
    container_name: tumtumpa
    restart: unless-stopped
    environment:
      - LASTFM_API_KEY=${LASTFM_API_KEY}
    # read_only: true
    # tmpfs:
    #   - /tmp
    # user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./logs/tumtumpa:/app/logs
    networks:
      - musica

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    restart: unless-stopped
    command:
      - '--nginx.scrape-uri=http://nginx:8080/stub_status'
    depends_on:
      - nginx
    networks:
      - musica

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8085:80"
      - "8443:443"
    environment:
      - CROWDSEC_ENABLE=true
      - CROWDSEC_LABELS_TYPE=nginx
      - METRICS_ALLOWED_IP=${METRICS_ALLOWED_IP}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - escuchowsky
      - tumtumpa
    volumes:
      - /home/docker_webs/contenedores/nginx/logs/nginx:/var/log/nginx
    networks:
      musica:
        ipv4_address: 172.20.0.10

networks:
  musica:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
