# 00_zones.conf — Rate limiting zones (cargado primero por orden alfabético)
limit_req_zone $binary_remote_addr zone=heavy:10m rate=6r/m;
limit_req_zone $binary_remote_addr zone=cover:10m rate=60r/m;
limit_req_zone $binary_remote_addr zone=page:10m  rate=60r/m;
