# internal.conf — endpoints internos solo accesibles desde la red musica
# Sin mapeo de puertos al exterior, solo uso interno entre contenedores

server {
    listen 8080;
    server_name _;
    access_log off;

    location /stub_status {
        stub_status;
        allow 172.20.0.0/24;
        deny all;
    }
}
